export const AGENT_ACTIONS = {
    SELECT_AGENT: "SELECT_AGENT",
    SELECT_AGENT_DASHBOARD: "SELECT_AGENT_DASHBOARD",
    SELECT_AGENT_DASHBOARD_COMPLETE: "SELECT_AGENT_DASHBOARD_COMPLETE",
    GET_ALL: "GET_ALL",
    GET_ALL_COMPLETE: "GET_ALL_COMPLETE",
    POST_AGENT_TRANSACTION: "POST_AGENT_TRANSACTION",
    POST_AGENT_TRANSACTION_COMPLETE: "POST_AGENT_TRANSACTION_COMPLETE",
    POST_AGENT_TRANSACTION_ERROR: "POST_AGENT_TRANSACTION_ERROR",
    REFRESH_AGENT_DASHBOARD: "REFRESH_AGENT_DASHBOARD",
    REFRESH_AGENT_DASHBOARD_COMPLETE: "REFRESH_AGENT_DASHBOARD_COMPLETE"
}