

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CardPeak.Repository.EF
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using CardPeak.Domain;


public partial class CardPeakDbContext : DbContext
{
    public CardPeakDbContext()
        : base("name=CardPeakDbContext")
    {

        this.Configuration.LazyLoadingEnabled = false;

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Account> Accounts { get; set; }

    public virtual DbSet<Agent> Agents { get; set; }

    public virtual DbSet<ApprovalTransaction> ApprovalTransactions { get; set; }

    public virtual DbSet<BatchUpload> BatchUploads { get; set; }

    public virtual DbSet<DebitCreditTransaction> DebitCreditTransactions { get; set; }

    public virtual DbSet<Rate> Rates { get; set; }

    public virtual DbSet<Reference> References { get; set; }

    public virtual DbSet<ReferenceType> ReferenceTypes { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<BatchFileConfiguration> BatchFileConfiguration { get; set; }

    public virtual DbSet<Team> Teams { get; set; }

    public virtual DbSet<TeamPlacement> TeamPlacements { get; set; }

    public virtual DbSet<DefaultRate> DefaultRates { get; set; }

    public virtual DbSet<AgentPayout> AgentPayout { get; set; }

}

}

